### ISSUE TITLE
"Allow the computer to access information on xxxxx"

### ISSUE THREAD

**Issue by prolok** [libimobiledevice-win32/imobiledevice-net#82]
If I have not "Allow the computer to access information on 'iPod'" via iTunes, I will get `iMobileDevice.Lockdown.LockdownException: 'An Lockdown error occurred. The error code was InvalidConf'` when calling `lockdown.lockdownd_client_new_with_handshake(deviceHandle, out lockdownHandle, "Quamotion").ThrowOnError();`.

Is it possible to do the "allow" action via the library, so that the user no need to open the iTunes (but of course have installed it)?

Or better..... is it possible that not requiring the user install iTunes, just included everything in my C# application?

Thank you!

**Comment by qmfrederik** [comment]
You can only use imobiledevice-net/libimobiledevice if your device trusts your PC. Your device will block any connectivity the PC is not trusted. You cannot force a device to trust a PC from the PC itself; you really require a user action on the device. This is by design from Apple. 

You need the Apple Mobile Device Service installed on your PC. This contains the drivers and the multiplexer which manages connectivity between your PC and your device. This ships as part of iTunes, so you can't really get around having iTunes installed.
